// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkplaceTasks.Infrastructure.Data;

#nullable disable

namespace WorkplaceTasks.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkplaceTasks.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkplaceTasks.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d38cca2f-a50d-435e-8fd8-f071617a2061"),
                            CreatedAt = new DateTime(2025, 10, 30, 19, 10, 29, 526, DateTimeKind.Utc).AddTicks(3380),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$msBrPP6Xgh0OO8n5LsqSfekAZiU/ufQ8KqvB.5ZC4HmnVS4NUIhiG",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("be46fcc6-d556-41ee-8034-fc454dcea648"),
                            CreatedAt = new DateTime(2025, 10, 30, 19, 10, 29, 627, DateTimeKind.Utc).AddTicks(6050),
                            Email = "manager@example.com",
                            PasswordHash = "$2a$11$nG8zwY8PNQMgHE9aFk.7x./UCpUENO3r5JviNReMpn0Vm7VHWvFRG",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("5fee76f9-1743-42e3-bdbc-29cf76f02dc1"),
                            CreatedAt = new DateTime(2025, 10, 30, 19, 10, 29, 725, DateTimeKind.Utc).AddTicks(5010),
                            Email = "member@example.com",
                            PasswordHash = "$2a$11$CIfEGeCFoZjHm0mkSI7uzOcxAOPUpoABbbSl7hGh/7CboBBM4ZNb.",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
